language: node_js
cache:
  directories:
    - node_modules #mantener en cache estos modulos
    - ~/.npm

node_js:
  - '12'

git:
  depth: 3

script:
  - yarn build

notifications:
  email:
    recipients:
    -  milton37aa@gmail.com
    -  milton.fi@hotmail.com
    on_success: always
    on_failure: always
  slack: flashboysmonitor:CVZvYISJNtWfV3imP0zmjDiF

deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: dist/
  target_branch: gh-pages
  commit_message: "Deploy of the project"
  on:
    branch: master